add guide template and update readme
elmiko/okd-deployment-configuration-guides pull request #7
Opened 2021-03-24 23:51 UTC by elmiko

this change proposed a new template for guide creation, it also updates
the readme to better define the focus of the guides and the template
usage.

2021-03-24 23:52 UTC, elmiko commented
cc @bdlink @erikbgithub ptal

2021-03-25 10:10 UTC, erikbgithub requested changes
I really like the list of considerations taken for the template. E.g., the split of Infra requirements into subsections will enable authors to think more clearly about their setup before sharing a guide. The same goes for enabling authors not to forget about upgrade and day2 ops situations.

I've added a few discussion points and change request as comments.

And altogether, in regards to writing style, I personally would prefer a more authoritative style than a tutorial style. We demand quality inputs from ourselves and others, and we can stand by that demand with confidence.

Also currently, it might not be clear for someone applying the template, where they should leave text in there and where it should be replaced by user input. A great example that gave me some enlightenment in that area was the [Podman Issue template](https://github.com/containers/podman/blob/master/.github/ISSUE_TEMPLATE.md).

As an idea:

```
### Networking

Following are the list of networking requirements to implement this guide: [addressing the user, not the guide author, thereby already helping the author structure their text]

''' [not using backticks, as the whole example is already in backticks]
<TODO: replace content of this block> [here addressing the guide author with <> blocks]

 * Gigabit LAN between workstation, bootstrap, master node
 * Gigabit LAN between master and worker nodes
 * Gigabit LAN between master and router
 * the LAN's and workstation's nameservice delegating requests of the wildcard domain to the master nodes
 * 2 x GCP Load Balancers
'''
```

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +last-updated: "2021-03-24"
Do we also want to state explicit assumptions about expiry dates and/or versions?

Examples:
 *  `wontwork-if: <feature comes or goes away>`
 *  `wontwork-with: <version X.Y or later>`
 *  `wontwork-when: <assumed expiry date>`

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +Hello! This is the template for creating new OKD deployment configuration guides.
Here, we could link to a small list of comprehensive guides that include all steps, thereby enabling other community members to drop their setups more in form of a note with only the necessary steps. E.g., `[OKD deployment](/path/to/standard-guides)`

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +First steps
I would add a colon behind.

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +* For example, An HTTP server available to serve ignition files
I think, this is usually the hardest part to think about, since one doesn't easily remember the things one did before starting the project. Therefore I really like the example. Maybe we could add more.

Looking at Charro's guide, I really liked:
 * the host setup part
 * and the list of environment variables with explanation.

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +### Target Audience
I would lift this in the hierarchy and put it as the first section. It might be used by readers to determine if this guide is useful for them or not.

2021-03-25 10:10 UTC, erikbgithub commented on guide-template.md
> +How did you install your cluster? Are there any special considerations that should be made before attempting
`made, before`

2021-03-25 13:16 UTC, elmiko commented on guide-template.md
> +### Target Audience
good suggestion

2021-03-25 13:16 UTC, elmiko commented on guide-template.md
> +* For example, An HTTP server available to serve ignition files
i could expand this list to include more items like Charro has used

2021-03-25 13:17 UTC, elmiko commented on guide-template.md
> +Hello! This is the template for creating new OKD deployment configuration guides.
would suggest linking to the IPI default guides or did you have something else in mind?

2021-03-25 13:18 UTC, elmiko commented on guide-template.md
> +last-updated: "2021-03-24"
my preference would be to keep it simple for now, i think the last updated date makes it clear when it was touched last. i do like the idea of adding more metadata here, but i would like to defer that decision until we could talk with a larger group about how we want to use those values.

2021-03-25 13:19 UTC, elmiko commented on guide-template.md
> +How did you install your cluster? Are there any special considerations that should be made before attempting
that doesn't seem correct to me

2021-03-25 13:20 UTC, elmiko commented
thanks for the great review @erikbgithub !

> And altogether, in regards to writing style, I personally would prefer a more authoritative style than a tutorial style. We demand quality inputs from ourselves and others, and we can stand by that demand with confidence. What do you think about this?

i personally prefer a lighter tone for these templates, but i don't have an objection to making it more authoritative.

> 
> Also currently, it might not be clear for someone applying the template, where they should leave text in there and where it should be replaced by user input. A great example that gave me some enlightenment in that area was the [Podman Issue template](https://github.com/containers/podman/blob/master/.github/ISSUE_TEMPLATE.md). I think I would need to do it in a separate PR, but would go through the subsections and do that with your agreement.
> 
> As an idea:
> 
> ```
> ### Networking
> 
> Following are the list of networking requirements to implement this guide: [addressing the user, not the guide author, thereby already helping the author structure their text]
> 
> ''' [not using backticks, as the whole example is already in backticks]
> <TODO: replace content of this block> [here addressing the guide author with <> blocks]
> 
>  * Gigabit LAN between workstation, bootstrap, master node
>  * Gigabit LAN between master and worker nodes
>  * Gigabit LAN between master and router
>  * the LAN's and workstation's nameservice delegating requests of the wildcard domain to the master nodes
>  * 2 x GCP Load Balancers
> '''
> ```

solid idea, i'll try to work this in for the sections that have example lists

2021-03-25 23:46 UTC, elmiko commented on guide-template.md
> +Hello! This is the template for creating new OKD deployment configuration guides.
reading this again, i think i get what you are suggesting. unfortunately, i don't think we have a guide yet that will really conform to the template. i am certainly happy to have a todo about adding links here, i think it's a great idea.

2021-03-26 00:14 UTC, elmiko commented
updated to address comments. @erikbgithub i tried to fix the things that made sense to me. i think we might have to defer some of the other changes until later though.

2021-03-26 00:44 UTC, elmiko commented
ok, one more push for tonight. i added even more `TODO` blocks, let me know what you think @erikbgithub.

2021-03-28 07:52 UTC, erikbgithub commented on guide-template.md
> +How did you install your cluster? Are there any special considerations that should be made before attempting
Interesting. Even after looking at it again, I still would. But not sure, how we could figure out which would be correct, if there even is a single correct way to do it.

2021-03-28 07:53 UTC, erikbgithub commented
Thanks, @elmiko. +1 from me.

2021-03-29 13:41 UTC, elmiko commented on guide-template.md
> +How did you install your cluster? Are there any special considerations that should be made before attempting
i tried to make it clearer by removing a couple words, how does that look?

2021-03-30 06:36 UTC, erikbgithub commented on guide-template.md
> +How did you install your cluster? Are there any special considerations that should be made before attempting
Awesome, thanks @elmiko!

2021-03-30 13:10 UTC, merged